<a href="https://colab.research.google.com/github/369koushil/ML_algos/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification

In [ ]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,n_clusters_per_class=1,random_state=36)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.75,test_size=0.25,random_state=36)

In [ ]:
logistic=LogisticRegression()

In [ ]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_predicted=logistic.predict(x_test)


In [ ]:
logistic.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'deprecated',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
print("Accuracy\n",accuracy_score(y_test,y_predicted))
print("Confusion matrix\n",confusion_matrix(y_test,y_predicted))
print("classification rpeort\n",classification_report(y_test,y_predicted))

Accuracy
 0.988
Confusion matrix
 [[117   3]
 [  0 130]]
classification rpeort
               precision    recall  f1-score   support

           0       1.00      0.97      0.99       120
           1       0.98      1.00      0.99       130

    accuracy                           0.99       250
   macro avg       0.99      0.99      0.99       250
weighted avg       0.99      0.99      0.99       250



In [ ]:
%pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
wine = fetch_ucirepo(id=109)

# data (as pandas dataframes)
X = wine.data.features
y = wine.data.targets.iloc[:, 0]

# metadata
print(wine.metadata)

# variable information
print(wine.variables)


{'uci_id': 109, 'name': 'Wine', 'repository_url': 'https://archive.ics.uci.edu/dataset/109/wine', 'data_url': 'https://archive.ics.uci.edu/static/public/109/data.csv', 'abstract': 'Using chemical analysis to determine the origin of wines', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 178, 'num_features': 13, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1992, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C5PC7J', 'creators': ['Stefan Aeberhard', 'M. Forina'], 'intro_paper': {'ID': 246, 'type': 'NATIVE', 'title': 'Comparative analysis of statistical pattern recognition methods in high dimensional settings', 'authors': 'S. Aeberhard, D. Coomans, O. Vel', 'venue': 'Pattern Recognition', 'year': 1994, 'journal': None, 'DOI': '10.1016/0031-3203(94)90145-7', 'URL': 'https:

In [ ]:
X.isnull().sum()
y.isnull().sum()

np.int64(0)

In [ ]:
y.iloc[:,:1].value_counts()

class
2        71
1        59
3        48
Name: count, dtype: int64

In [ ]:
X.shape

(178, 13)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.75,test_size=0.25,random_state=36)

In [ ]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV,StratifiedKFold

In [ ]:
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.0, 0.25, 0.5, 0.75, 1.0],
    'penalty': ['elasticnet'],
    'solver': ['saga']
}

stratified_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [ ]:
logisticCV=GridSearchCV(LogisticRegression(),param_grid,cv=stratified_cv)

In [ ]:
y_predicted=logisticCV.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [ ]:
y_predicted=logisticCV.predict(x_test)

In [ ]:
print("Accuracy\n",accuracy_score(y_test,y_predicted))
print("Confusion matrix\n",confusion_matrix(y_test,y_predicted))
print("classification rpeort\n",classification_report(y_test,y_predicted))

Accuracy
 0.6888888888888889
Confusion matrix
 [[15  1  0]
 [ 2 14  0]
 [ 3  8  2]]
classification rpeort
               precision    recall  f1-score   support

           1       0.75      0.94      0.83        16
           2       0.61      0.88      0.72        16
           3       1.00      0.15      0.27        13

    accuracy                           0.69        45
   macro avg       0.79      0.66      0.61        45
weighted avg       0.77      0.69      0.63        45



In [ ]:
logisticCV.best_estimator_

LogisticRegression(C=0.01, l1_ratio=0.0, penalty='elasticnet', solver='saga')